# Generated by Django 5.1.6 on 2025-03-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='interest_rate',
            field=models.FloatField(help_text='Yearly interest rate in %'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='tenure',
            field=models.IntegerField(help_text='Tenure in months'),
        ),
    ]
