# Generated by Django 5.1.6 on 2025-03-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_alter_loan_interest_rate_alter_loan_tenure'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='monthly_installment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='loan',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='loan',
            name='total_interest',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
